@url = http://localhost
#@url = http://localhost:5000

### GET first chunk
GET {{url}}/download?file=downloader-example.png&chunk=1

### Get second chunk
GET {{url}}/download?file=downloader-example.png&chunk=2


### Get second to last chunk
GET {{url}}/download?file=downloader-example.png&chunk=575

### Get last chunk
GET {{url}}/download?file=downloader-example.png&chunk=576

### Attempt to get chunk beyond last chunk
GET {{url}}/download?file=downloader-example.png&chunk=577
